version: '2'
volumes:
  base_data:
  db_data:
services:
  base:
    image: debug
    build:
      context: .
      dockerfile: debug.docker
    volumes:
      - base_data:/var/easygoing
      - .:/code
    links:
      - db
      - cache
    command:
      >
        bash -c "
        chown -R user:user /var/easygoing &&
        su user -c 'mkdir -p /var/easygoing/logs' &&
        su user -c 'touch /var/easygoing/logs/django.log' &&
        chmod -R uo+rw /var/easygoing;
        su user -c 'python wait_for.py db 5432' &&
        su user -c 'python wait_for.py cache 6379' &&
        su user -c 'python manage.py migrate'"
    environment:
      DEBUG: 'True'
      DJANGO_ALLOWED_HOSTS: '*'
      DB_ENGINE: 'django.db.backends.postgresql'
      DB_NAME: 'postgres'
      DB_USER: 'postgres'
      DB_HOST: 'db'
      DB_PORT: '5432'
  web:
    image: debug
    command:
      >
        bash -c "
        python wait_for.py db 5432 &&
        python wait_for.py cache 6379 &&
        python manage.py runserver 0.0.0.0:8000"
    user: user
    environment:
      DEBUG: 'True'
      DJANGO_ALLOWED_HOSTS: '*'
      DB_ENGINE: 'django.db.backends.postgresql'
      DB_NAME: 'postgres'
      DB_USER: 'postgres'
      DB_HOST: 'db'
      DB_PORT: '5432'
    volumes_from:
      - base
    ports:
      - '8000:8000'
    depends_on:
      - base
    links:
      - db
      - cache
  cache:
    image: redis:3.2
  db:
    image: postgres:9.6
    volumes:
      - db_data:/var/lib/postgresql/data