version: '2'
services:
  gunicorn:
    command:
      >
        /bin/sh -c "
        python wait_for.py db 5432 &&
        python wait_for.py cache 6379 &&
        gunicorn easygoing.wsgi:application
        --name easygoing_gunicorn
        --bind=unix:/var/easygoing/gunicorn.sock
        --user=user --group=user
        --log-level=info
        --error-logfile=/var/easygoing/logs/gunicorn-error.log
        --access-logfile=/var/easygoing/logs/gunicorn-access.log"
    environment:
      DJANGO_ALLOWED_HOSTS: '{{fqdn}}'
      SECRET_KEY: '{{secret_key}}'