---
- name: Install docker requirements
  apt: pkg='apt-transport-https,ca-certificates,curl,python-software-properties' update_cache=yes
  ignore_errors: yes
  register: apt_result

- name: Retry if needed using command apt-get update
  command: aptitude install -y apt-transport-https ca-certificates curl python-software-properties
  become_user: root
  when: apt_result|failed
  register: apt_result

- name: Add docker apt keys
  apt_key: keyserver='pool.sks-keyservers.net' id=9DC858229FC7DD38854AE2D88D81803C0EBFCD88
  when: apt_result|success
  retries: 3
  delay: 1
  register: key_added

- name: Add docker repository
  apt_repository: repo='deb https://download.docker.com/linux/debian jessie stable' state=present
  when: key_added|success
  retries: 3
  delay: 1
  ignore_errors: yes
  register: repo_added

- name: Install docker
  apt: pkg=docker-ce update_cache=yes
  when: repo_added|success
  retries: 3
  delay: 1
  register: docker_installed

- name: Start Docker
  service: name=docker state=restarted
  when: docker_installed|success