# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 00:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('author_name', models.CharField(max_length=255)),
                ('author_email', models.EmailField(blank=True, max_length=254)),
                ('content', models.TextField()),
                ('taken_down', models.BooleanField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('edited', models.DateTimeField(null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('pl', 'Polski')], max_length=2)),
                ('title', models.CharField(max_length=1024)),
                ('content', models.TextField()),
                ('blog_post', models.BooleanField()),
                ('hidden', models.BooleanField()),
                ('comments_closed', models.BooleanField()),
                ('number_of_comments', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('header', models.TextField()),
                ('sidebar', models.TextField()),
                ('footer', models.TextField()),
                ('truncate_word_limit', models.IntegerField(null=True)),
                ('page_size', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Website Configuration',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stem.Post'),
        ),
    ]
