# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 23:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('edited', models.DateTimeField()),
                ('language', models.CharField(choices=[('en', 'English'), ('pl', 'Polski')], max_length=2)),
                ('title', models.CharField(max_length=4096)),
                ('content', models.TextField()),
                ('blog_post', models.BooleanField()),
                ('hidden', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('date', models.DateTimeField()),
                ('author_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=2048)),
                ('content', models.TextField()),
                ('taken_down', models.BooleanField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stem.Article')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sidebar', models.TextField()),
            ],
            options={
                'verbose_name': 'Website Configuration',
            },
        ),
    ]
